export default {
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    REMOVE_ALL_COMPLETED: "REMOVE_ALL_COMPLETED",
    EDIT_TODO: "EDIT_TODO",
    COMPLETE_TODO: "COMPLETE_TODO",
    COMPLETE_ALL: "COMPLETE_ALL",
    TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
    TOGGLE_ALL: "TOGGLE_ALL",

};
